### ISSUE TITLE
lab6 강의 녹화본 관련 질문드립니다

### ISSUE THREAD

**Issue by webserver3315** [ECE4278/lab6#1]
실습강의 녹화본을 참고하려고 했는데 업로드가 안되어있어서, 혹시 녹화본이 언제 업로드될 예정인지 알 수 있을까요?
감사합니다.

**Comment by dale40** [comment]
아이캠퍼스에 지금 업로드 했습니다.

**Comment by webserver3315** [comment]
답변 감사합니다
